import type { CSSProperties } from 'react';

const styles: Record<string, CSSProperties> = {
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '20px',
    paddingTop: '80px',
    paddingBottom: '40px',
    overflow: 'auto',
    overflowX: 'hidden',
    WebkitOverflowScrolling: 'touch',
    minHeight: 0,
    boxSizing: 'border-box',
  },
  loadingContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
  },
  loadingSpinner: {
    width: '48px',
    height: '48px',
    border: '4px solid rgba(255,255,255,0.1)',
    borderTopColor: '#1B7340',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  loadingText: {
    fontSize: '16px',
    color: 'rgba(255,255,255,0.6)',
  },
  stepContainer: {
    flex: '1 0 auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    maxWidth: '900px',
    margin: '0 auto',
    width: '100%',
    paddingBottom: '100px',
  },
  backButton: {
    alignSelf: 'flex-start',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'rgba(255,255,255,0.1)',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: '8px',
    padding: '10px 20px',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    marginBottom: '24px',
  },
  stepHeader: {
    textAlign: 'center',
    marginBottom: '32px',
    padding: '0 10px',
  },
  stepIcon: {
    width: '64px',
    height: '64px',
    borderRadius: '16px',
    background: 'linear-gradient(135deg, #1B7340 0%, #0d4a28 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ffffff',
    margin: '0 auto 20px',
  },
  stepTitle: {
    fontSize: 'clamp(22px, 5vw, 28px)',
    fontWeight: '700',
    color: '#ffffff',
    margin: '0 0 8px 0',
    textAlign: 'center',
  },
  stepSubtitle: {
    fontSize: '16px',
    color: 'rgba(255,255,255,0.6)',
    margin: 0,
  },
  categoryBadge: {
    display: 'inline-block',
    padding: '8px 16px',
    background: 'rgba(27, 115, 64, 0.2)',
    borderRadius: '20px',
    color: '#4ade80',
    fontSize: '14px',
    fontWeight: '600',
    marginBottom: '12px',
  },
  modelBadge: {
    display: 'inline-block',
    padding: '8px 16px',
    background: 'rgba(37, 99, 235, 0.2)',
    borderRadius: '20px',
    color: '#60a5fa',
    fontSize: '14px',
    fontWeight: '600',
    marginBottom: '12px',
  },
  categoryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: '12px',
    width: '100%',
    paddingBottom: '40px',
  },
  categoryCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '20px 16px',
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: '16px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  categoryIcon: { fontSize: '36px' },
  categoryName: { fontSize: '15px', fontWeight: '600', color: '#ffffff', textAlign: 'center' },
  categoryCount: { fontSize: '12px', color: 'rgba(255,255,255,0.5)' },
  modelGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '12px',
    width: '100%',
  },
  modelCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    padding: '20px 16px',
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: '16px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  modelInitial: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #2563eb 0%, #1e40af 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    fontWeight: '700',
    color: '#ffffff',
  },
  modelName: { fontSize: '15px', fontWeight: '600', color: '#ffffff', textAlign: 'center' },
  modelCount: { fontSize: '12px', color: '#4ade80', fontWeight: '600' },
  modelConfig: { fontSize: '11px', color: 'rgba(255,255,255,0.5)' },
  cabGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '12px',
    width: '100%',
  },
  cabCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '24px 16px',
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: '16px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  cabIcon: { fontSize: '36px' },
  cabName: { fontSize: '16px', fontWeight: '600', color: '#ffffff' },
  cabDesc: { fontSize: '12px', color: 'rgba(255,255,255,0.5)', textAlign: 'center' },
  formSection: {
    width: '100%',
    padding: '20px',
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '16px',
    border: '1px solid rgba(255,255,255,0.1)',
    boxSizing: 'border-box',
  },
  formIntro: {
    fontSize: '14px',
    color: 'rgba(255,255,255,0.9)',
    marginBottom: '20px',
    textAlign: 'center',
  },
  colorSelects: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
    marginBottom: '24px',
  },
  colorSelectGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  inputLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#ffffff',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  downPaymentDisclaimer: {
    fontSize: '10px',
    fontWeight: '500',
    color: 'rgba(255,255,255,0.7)',
    textTransform: 'none',
    letterSpacing: '0',
    marginLeft: '8px',
  },
  selectInput: {
    padding: '14px 16px',
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: '10px',
    color: '#ffffff',
    fontSize: '15px',
    cursor: 'pointer',
    width: '100%',
    boxSizing: 'border-box',
  },
  colorPreview: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 12px',
    background: 'rgba(0,0,0,0.2)',
    borderRadius: '8px',
    fontSize: '13px',
    color: 'rgba(255,255,255,0.8)',
  },
  colorSwatch: {
    width: '24px',
    height: '24px',
    borderRadius: '6px',
    border: '2px solid rgba(255,255,255,0.3)',
    flexShrink: 0,
  },
  continueButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    width: '100%',
    padding: '16px',
    background: 'linear-gradient(135deg, #2563eb 0%, #1e40af 100%)',
    border: 'none',
    borderRadius: '12px',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  budgetDisplay: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: '8px',
    marginBottom: '28px',
    flexWrap: 'wrap',
  },
  budgetValue: { fontSize: 'clamp(28px, 6vw, 36px)', fontWeight: '700', color: '#4ade80' },
  budgetSeparator: { fontSize: '16px', color: 'rgba(255,255,255,0.9)' },
  budgetLabel: { fontSize: '14px', color: 'rgba(255,255,255,0.9)' },
  sliderGroup: {
    marginBottom: '20px',
  },
  sliderLabel: {
    display: 'block',
    fontSize: '13px',
    color: '#ffffff',
    marginBottom: '8px',
  },
  slider: {
    width: '100%',
    height: '8px',
    borderRadius: '4px',
    appearance: 'none',
    background: 'rgba(255,255,255,0.1)',
    cursor: 'pointer',
  },
  downPaymentSection: {
    marginTop: '24px',
    marginBottom: '24px',
  },
  downPaymentOptions: {
    display: 'flex',
    gap: '8px',
    marginTop: '10px',
    flexWrap: 'wrap',
  },
  optionButton: {
    padding: '10px 14px',
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: '10px',
    color: '#ffffff',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    flex: '1 1 auto',
    minWidth: '70px',
    textAlign: 'center',
  },
  optionButtonActive: {
    background: 'rgba(27, 115, 64, 0.3)',
    borderColor: '#1B7340',
    color: '#4ade80',
  },
  tradeOptions: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '12px',
    marginBottom: '24px',
  },
  tradeCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '24px 16px',
    background: 'rgba(255,255,255,0.05)',
    border: '2px solid rgba(255,255,255,0.1)',
    borderRadius: '16px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  tradeCardActive: {
    background: 'rgba(27, 115, 64, 0.15)',
    borderColor: '#1B7340',
  },
  tradeIcon: { fontSize: '28px', color: '#4ade80' },
  tradeName: { fontSize: '16px', fontWeight: '600', color: '#ffffff', textAlign: 'center' },
  tradeDesc: { fontSize: '12px', color: 'rgba(255,255,255,0.5)', textAlign: 'center' },
  payoffSection: {
    padding: '16px',
    background: 'rgba(0,0,0,0.2)',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  payoffTitle: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '16px',
  },
  payoffOptions: {
    display: 'flex',
    gap: '12px',
    marginBottom: '16px',
    flexWrap: 'wrap',
  },
  payoffAmountGroup: {
    marginTop: '16px',
  },
  inputWrapper: {
    display: 'flex',
    alignItems: 'center',
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: '10px',
    marginTop: '8px',
    overflow: 'hidden',
  },
  inputPrefix: {
    padding: '14px 12px',
    background: 'rgba(255,255,255,0.05)',
    color: 'rgba(255,255,255,0.5)',
    fontSize: '16px',
    fontWeight: '600',
  },
  textInput: {
    flex: 1,
    padding: '14px 16px',
    background: 'transparent',
    border: 'none',
    color: '#ffffff',
    fontSize: '16px',
    outline: 'none',
    minWidth: 0,
  },
  searchButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    width: '100%',
    padding: '16px',
    background: 'linear-gradient(135deg, #1B7340 0%, #0d4a28 100%)',
    border: 'none',
    borderRadius: '12px',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: '700',
    cursor: 'pointer',
  },
  progressBar: {
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
    marginTop: '32px',
    marginBottom: '40px',
    paddingBottom: 'env(safe-area-inset-bottom, 20px)',
  },
  progressDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.2)',
  },
  progressDotActive: {
    background: '#1B7340',
    transform: 'scale(1.2)',
  },
  progressDotComplete: {
    background: '#4ade80',
  },
  buyingPowerSection: {
    marginTop: '24px',
    padding: '16px',
    background: 'rgba(0,0,0,0.3)',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  buyingPowerIntro: {
    fontSize: '14px',
    color: 'rgba(255,255,255,0.9)',
    marginBottom: '16px',
  },
  buyingPowerCard: {
    padding: '16px',
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '10px',
    marginBottom: '16px',
  },
  buyingPowerTitle: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  buyingPowerList: {
    listStyle: 'disc',
    paddingLeft: '20px',
    marginBottom: '16px',
    color: 'rgba(255,255,255,0.95)',
    fontSize: '14px',
    lineHeight: '1.8',
  },
  buyingPowerText: {
    fontSize: '14px',
    color: 'rgba(255,255,255,0.9)',
    marginBottom: '12px',
  },
  buyingPowerResult: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    padding: '12px 16px',
    background: 'rgba(74, 222, 128, 0.1)',
    borderRadius: '8px',
    marginBottom: '16px',
    fontSize: '14px',
    color: '#4ade80',
  },
  buyingPowerTotal: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    padding: '12px 16px',
    background: 'rgba(37, 99, 235, 0.15)',
    borderRadius: '8px',
    fontSize: '15px',
    color: '#60a5fa',
  },
  mathBreakdown: {
    padding: '16px',
    background: 'rgba(255,255,255,0.03)',
    borderRadius: '10px',
  },
  mathTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: 'rgba(255,255,255,0.95)',
    marginBottom: '10px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  mathList: {
    listStyle: 'disc',
    paddingLeft: '20px',
    color: 'rgba(255,255,255,0.9)',
    fontSize: '13px',
    lineHeight: '1.8',
  },
  disclaimer: {
    marginTop: '16px',
    textAlign: 'center',
    fontSize: '12px',
    color: 'rgba(255,255,255,0.7)',
    fontStyle: 'italic',
  },
};

export default styles;
