/**
 * VehicleDetail Component Styles
 */

import { CSSProperties } from 'react';

export const vehicleDetailStyles: Record<string, CSSProperties> = {
  container: {
    flex: 1,
    padding: '20px 40px',
    overflowY: 'auto',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'transparent',
    border: 'none',
    color: 'rgba(255,255,255,0.7)',
    fontSize: '14px',
    cursor: 'pointer',
    padding: '8px 0',
    marginBottom: '20px',
  },
  content: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '40px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  leftColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  mainImage: {
    height: '360px',
    borderRadius: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  vehicleImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: '20px',
  },
  imageInitial: {
    fontSize: '120px',
    fontWeight: '800',
    color: 'rgba(255,255,255,0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBadge: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    background: 'rgba(0,0,0,0.7)',
    borderRadius: '24px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#ffffff',
  },
  statusDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    background: '#4ade80',
  },
  quickSpecs: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
  },
  specItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '16px',
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '12px',
  },
  specIcon: {
    fontSize: '24px',
  },
  specLabel: {
    display: 'block',
    fontSize: '11px',
    fontWeight: '600',
    color: 'rgba(255,255,255,0.5)',
    textTransform: 'uppercase',
    marginBottom: '2px',
  },
  specValue: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '600',
    color: '#ffffff',
  },
  rightColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  vehicleHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  titleBlock: {
    flex: 1,
  },
  vehicleTitle: {
    fontSize: '32px',
    fontWeight: '700',
    color: '#ffffff',
    margin: 0,
    lineHeight: 1.2,
  },
  titleSeparator: {
    color: 'rgba(255,255,255,0.4)',
    fontWeight: '400',
  },
  subtitleRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '8px',
  },
  vehicleTrim: {
    fontSize: '16px',
    color: 'rgba(255,255,255,0.6)',
    margin: 0,
    textTransform: 'uppercase',
  },
  stockInfo: {
    textAlign: 'right' as const,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  stockLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: 'rgba(255,255,255,0.4)',
    textTransform: 'uppercase',
  },
  stockNumber: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#ffffff',
  },
  colorRow: {
    display: 'flex',
    gap: '24px',
  },
  colorItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  colorSwatch: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    border: '2px solid rgba(255,255,255,0.2)',
  },
  colorLabel: {
    display: 'block',
    fontSize: '11px',
    fontWeight: '600',
    color: 'rgba(255,255,255,0.5)',
    textTransform: 'uppercase',
  },
  colorValue: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '500',
    color: '#ffffff',
  },
  pricingCard: {
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '16px',
    padding: '24px',
  },
  priceRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  msrpLabel: {
    fontSize: '14px',
    color: 'rgba(255,255,255,0.5)',
    fontWeight: '500',
  },
  msrpValue: {
    fontSize: '16px',
    color: 'rgba(255,255,255,0.5)',
    textDecoration: 'line-through',
  },
  rebateRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '6px 0',
  },
  rebateName: {
    fontSize: '13px',
    color: 'rgba(255,255,255,0.6)',
  },
  rebateAmount: {
    fontSize: '13px',
    color: '#4ade80',
    fontWeight: '600',
  },
  priceDivider: {
    height: '1px',
    background: 'rgba(255,255,255,0.1)',
    margin: '12px 0',
  },
  yourPriceLabel: {
    fontSize: '16px',
    color: '#ffffff',
    fontWeight: '600',
  },
  yourPriceValue: {
    fontSize: '32px',
    color: '#4ade80',
    fontWeight: '700',
  },
  savingsBadge: {
    background: 'rgba(74, 222, 128, 0.1)',
    color: '#4ade80',
    padding: '8px 16px',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    textAlign: 'center' as const,
    marginTop: '12px',
  },
  paymentsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
    marginTop: '16px',
  },
  paymentOption: {
    background: 'rgba(255,255,255,0.05)',
    padding: '16px',
    borderRadius: '12px',
    textAlign: 'center' as const,
  },
  paymentType: {
    display: 'block',
    fontSize: '11px',
    fontWeight: '600',
    color: 'rgba(255,255,255,0.5)',
    textTransform: 'uppercase',
    marginBottom: '4px',
  },
  paymentAmount: {
    display: 'block',
    fontSize: '24px',
    fontWeight: '700',
    color: '#ffffff',
  },
  paymentTerm: {
    display: 'block',
    fontSize: '12px',
    color: 'rgba(255,255,255,0.5)',
    marginTop: '2px',
  },
  featuresCard: {
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '16px',
    padding: '24px',
  },
  featuresTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '16px',
  },
  featuresGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '8px',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    color: 'rgba(255,255,255,0.8)',
  },
  featureCheck: {
    color: '#4ade80',
    fontSize: '16px',
  },
  actionsColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '8px',
  },
  primaryButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    padding: '18px 32px',
    background: 'linear-gradient(135deg, #1B7340 0%, #0d4a28 100%)',
    border: 'none',
    borderRadius: '12px',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  secondaryButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    padding: '14px 24px',
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: '12px',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  vinRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 16px',
    background: 'rgba(255,255,255,0.03)',
    borderRadius: '8px',
    marginTop: '8px',
  },
  vinLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: 'rgba(255,255,255,0.4)',
  },
  vinValue: {
    fontSize: '13px',
    fontWeight: '500',
    color: 'rgba(255,255,255,0.7)',
    fontFamily: 'monospace',
  },
  // Confirmation screen styles
  confirmationOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(0,0,0,0.9)',
    zIndex: 1000,
  },
  confirmationCard: {
    background: 'linear-gradient(135deg, rgba(27,115,64,0.2) 0%, rgba(13,74,40,0.2) 100%)',
    border: '1px solid rgba(74, 222, 128, 0.3)',
    borderRadius: '24px',
    padding: '48px',
    textAlign: 'center' as const,
    maxWidth: '500px',
    width: '90%',
  },
  confirmationIcon: {
    width: '80px',
    height: '80px',
    background: 'linear-gradient(135deg, #1B7340 0%, #0d4a28 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 24px',
    color: '#ffffff',
    animation: 'checkmark 0.5s ease forwards',
  },
  confirmationTitle: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: '12px',
  },
  confirmationSubtitle: {
    fontSize: '16px',
    color: 'rgba(255,255,255,0.7)',
    marginBottom: '32px',
    lineHeight: 1.5,
  },
  confirmationVehicle: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    background: 'rgba(255,255,255,0.05)',
    padding: '16px',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  confirmationThumb: {
    width: '80px',
    height: '60px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmationInitial: {
    fontSize: '24px',
    fontWeight: '700',
    color: 'rgba(255,255,255,0.3)',
  },
  confirmationVehicleInfo: {
    textAlign: 'left' as const,
  },
  confirmationVehicleName: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#ffffff',
  },
  confirmationStock: {
    fontSize: '13px',
    color: 'rgba(255,255,255,0.5)',
  },
  estimatedTime: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    fontSize: '14px',
    color: 'rgba(255,255,255,0.6)',
  },
};
